### ISSUE TITLE
Translations / Langcode 

### ISSUE THREAD

**Issue by scazzy** [bombayworks/currycms#14]
Feature request:
1. Would like to see the LangCode used for languages in translations for quick access. (Screenshot below)
2. If the site uses/has multiple languages, could have a Default Language

Screenshot::1
![image](https://f.cloud.github.com/assets/1681586/1731178/face7a4a-62fc-11e3-8577-b228d014f24e.png)

**Comment by josedsilva** [comment]
Please close this issue.
