### ISSUE TITLE
Package manager does not upgrade an installed package

### ISSUE THREAD

**Issue by josedsilva** [bombayworks/currycms#18]
PLEASE IGNORE THIS ISSUE IF YOU ARE SWITCHING TO COMPOSER OR ANOTHER PACKAGE MANAGER.

Package manager reports "This package is already installed and is the latest version or newer." when trying to Upgrade an already installed package.

Currently, package must be uninstalled and re-installed to do an upgrade.

![2014-01-30 12_05_58-package manager _ curry cms product development _ curry cms](https://f.cloud.github.com/assets/712432/2037756/16d82f2c-8979-11e3-9eee-6971f97c6414.png)

![2014-01-30 12_06_57-package manager _ curry cms product development _ curry cms](https://f.cloud.github.com/assets/712432/2037759/1bbd15f2-8979-11e3-9ddb-714ac6a3e820.png)

**Comment by deadbeef84** [comment]
Curry package manager has been removed, in favour of composer.
