### ISSUE TITLE
Feature Request: Collapsible SubForms (Fieldsets) in MultiForms

### ISSUE THREAD

**Issue by scazzy** [bombayworks/currycms#19]
![image](https://f.cloud.github.com/assets/1681586/2048398/20b2ef2e-8a45-11e3-9828-36311e389f9d.png)

Feature request

1. This should have - Allowing MultiForm Fieldsets (Like accordion, plus/minus) to be collapsible, and pushing the "Delete" on the right or somewhere.
2. This would be good to have - Allowing Fieldsets around form elements added in DisplayGroups to be collapsible if said to be.

Both were faced mostly in Page Modules, where each subForm have a lot of data, and all elements are open always taking lot of space to scroll.

Screendump: https://db.tt/4oiwEYiQ

**Comment by josedsilva** [comment]
Please close this issue if it's resolved.
