### ISSUE TITLE
No vertical inheritance for module content when a Page template is applied to a page.

### ISSUE THREAD

**Issue by josedsilva** [bombayworks/currycms#23]
When a Page template (a.k.a  Layout page) is applied to a page, the modules inherit content from the applied layout page and not from the parent pages in the vertical page tree.
This makes it difficult to edit content of a module on a "parent" page (which has an applied layout page) since this content will not be inherited to any of it's subpages (i.e. no vertical inheritance). A module on a child/sub page will inherit content from its applied layout page (i.e. lateral inheritance) and not from the parent page. This is a major issue that needs to be resolved.
However, If a module is created on a page and it's content edited, this content will become available to it's "direct" descendants (i.e. direct vertical inheritance exists).

This looks like a design flaw. Can I propose a new design to tackle this issue? You need to debate it.
A page should not inherit content from Layout pages. A layout page should be a template that specifies, what twig template to use and which modules to insert in the placeholders. It can use the module order but not the content. Content should be created either on the page or should come from the parent page(s).

**Comment by deadbeef84** [comment]
I've thought about this too. However, I'm not sure it's a major issue, and if it is, you can always inherit from parent page instead of a page template. I think inheriting layout from one page and content from another will be too confusing. It should also be noted that it can sometimes be solved using metadata, as this supports both inheritance from base page and parent page.

**Comment by josedsilva** [comment]
Nope, metadata created on an ancestor page does not get inherited to a subpage if both ancestor page and subpage have layout templates.
I agree with you on the inheritance issue - create the modules on the ancestor page, though this has to be done multiple times. Maybe if page struct is well planned, this issue can be taken care of.
Issue closed.
