### ISSUE TITLE
How to Install Curry CMS 

### ISSUE THREAD

**Issue by GaneshKandu** [bombayworks/currycms#26]
How to Install Curry CMS ??
or 
link of installation docs

**Comment by deadbeef84** [comment]
First you'll need to choose whether to use the stable version, 1.1, or the development version 2.0, I would recommend sticking with 1.1 for now as 2.0 is currently not very functional :)

As for installing, follow the instructions in the readme with one minor adjustment, leave out the --stability=dev flag.

* [Install composer](http://getcomposer.org)
* Create project skeleton and install dependencies `php composer.phar create-project bombayworks/currycms-project-base <directory>`
* Create curry symlink in `<directory>` `ln -s vendor/bombayworks/currycms curry`
* Make the `<directory>/www` folder accessible and enable URL rewriting to index.php
* Navigate to http://yourhost/admin.php

Please note that these instructions assumes that you have a working LAMP/MAMP (or equivalent) installation.

Let me know if you have any problems!

**Comment by GaneshKandu** [comment]
Thx
